### ISSUE TITLE
[feature request] Travis: show packages version list.

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/mate-dev-scripts#28]
@mate-desktop/core-team 

Feature request for travis:

Show the version of packages required (without dependencies, if possible)

maybe with more steps with `install_command` ?

(`dpkg -l packages_required` for debian/ubuntu and `pacman -Q packages_required` for arch ?)

https://github.com/mate-desktop/mate-dev-scripts/blob/master/travis/docker-build#L824

We can see this info in fedora, but it is hidden for other distros

screenshot of fedora, engrampa build:

![2019-10-16_11-15](https://user-images.githubusercontent.com/7734191/66905578-6535b780-f006-11e9-8792-2cc35d0fbaa0.png)

**Comment by yetist** [comment]
For example, the line in `.travis.yml` is that:
```
  - ./docker-build --name ${DISTRO} --config .travis.yml --install
```

The `-l` parameter specifies the total number of output lines. The default value is 100. You can set it to a larger number to see more output lines:

```
  - ./docker-build --name ${DISTRO} -l 2000 --config .travis.yml --install

```

Or add more `-v` options on the command line to get all the output lines:
```
  - ./docker-build --name ${DISTRO} -vvvv --config .travis.yml --install

```
