### ISSUE TITLE
mate-desktop.dev websites aren't working

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/mate-dev-scripts#31]
I noticed since yesterday the `mate-desktop.dev` websites aren't working

@yetist do you know why?

EDIT: removing the `CNAME` file in `gh-pages` branch makes working the sites `mate-desktop.github.io/repository`

**Comment by yetist** [comment]
Thanks for reminding me. I forgot to renew my account and almost lost my domain name. Fortunately, during the redemption period, I just completed the renewal and reset the DNS records. We need to check whether all domain names are valid.

**Comment by sc0w** [comment]
Thanks!

in my tests all are working now, but these aren't working:

https://libmatemixer.mate-desktop.dev

https://mate-utils.mate-desktop.dev

**Comment by yetist** [comment]
All done.

**Comment by sc0w** [comment]
@yetist Thanks a lot!
